# Generated by Django 5.0.3 on 2024-03-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
